# Generated by Django 5.0.6 on 2024-07-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
    ]
